// Code generated by mockery v2.1.0. DO NOT EDIT.

package dbscan

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// mockStartScannerFunc is an autogenerated mock type for the startScannerFunc type
type mockStartScannerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: rs, dstValue
func (_m *mockStartScannerFunc) Execute(rs *RowScanner, dstValue reflect.Value) error {
	ret := _m.Called(rs, dstValue)

	var r0 error
	if rf, ok := ret.Get(0).(func(*RowScanner, reflect.Value) error); ok {
		r0 = rf(rs, dstValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
